# Generated by Django 4.0.3 on 2022-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='CreatedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
